ALTER TABLE users ADD COLUMN username VARCHAR(255) UNIQUE AFTER id;
ALTER TABLE users ADD COLUMN password_digest VARCHAR(255) AFTER email;
ALTER TABLE users ADD COLUMN role VARCHAR(50) DEFAULT 'user'; 